# =========================================================================
# Archivo de Entorno Conda - Configuración Simplificada
# =========================================================================
#
# NOTA IMPORTANTE: Este archivo ahora usa requirements.txt como fuente principal
# de dependencias pip. Esto evita duplicación y divergencia.
#
# USO:
#   conda env create -f environment.yml          # Crear entorno
#   conda activate dl-gpu                        # Activar entorno
#   conda env update -f environment.yml --prune  # Actualizar entorno
#
# ESTRUCTURA:
#   1. Dependencias conda esenciales (Python, pip, compiladores)
#   2. Paquetes pip desde requirements.txt
#
# =========================================================================

name: dl-gpu

channels:
  - conda-forge
  - defaults

dependencies:
  # ====================================
  # Dependencias Conda Core (Esenciales)
  # ====================================

  # Python y gestión de paquetes
  - python=3.10.18
  - pip>=25.0
  - setuptools>=78.0
  - wheel>=0.45

  # Compiladores y bibliotecas del sistema (Windows)
  - vs2015_runtime  # Visual Studio runtime necesario en Windows

  # Certificados SSL
  - ca-certificates
  - openssl>=3.5

  # ====================================
  # Paquetes pip desde requirements.txt
  # ====================================
  - pip:
      # Instalar todas las dependencias desde requirements.txt
      - -r file:requirements.txt

      # Dependencias adicionales de desarrollo (no en requirements.txt)
      - pydocstyle>=6.3.0
      - detect-secrets>=1.4.0
      - nbstripout>=0.7.0

# =========================================================================
# NOTAS TÉCNICAS:
# =========================================================================
#
# 1. SIMPLIFICACIÓN:
#    - Se redujeron ~270 líneas a ~60 líneas
#    - Una sola fuente de verdad: requirements.txt
#    - Fácil mantenimiento y actualización
#
# 2. DEPENDENCIAS CONDA vs PIP:
#    - Conda: Solo paquetes esenciales del sistema (Python, compiladores, SSL)
#    - Pip: Todas las dependencias de aplicación (desde requirements.txt)
#
# 3. COMPATIBILIDAD:
#    - Funciona en Windows/Linux/macOS
#    - GPU support: TensorFlow 2.10 detecta CUDA automáticamente
#
# 4. ACTUALIZACIÓN:
#    - Modificar requirements.txt para dependencias de aplicación
#    - Modificar environment.yml solo para cambios de Python o sistema
#
# 5. ALTERNATIVA (sin conda):
#    - python -m venv venv
#    - venv\Scripts\activate  # Windows
#    - pip install -r requirements.txt
#
# =========================================================================
