# Configuración del Sistema de Detección de Enfermedades del Maíz
# Archivo de configuración central para MobileNetV3Large optimizado

# Configuración del modelo base MobileNetV3Large
model:
  name: "MobileNetV3Large"          # Arquitectura utilizada
  input_shape: [224, 224, 3]       # Dimensiones de entrada (alto, ancho, canales)
  alpha: 1.0                       # Factor de escala del modelo (1.0 = tamaño completo)
  minimalistic: false              # Versión minimalista (false = versión completa)
  include_top: true                # Incluir capa de clasificación original (se modifica en el código)
  pooling: "avg"                   # Tipo de pooling global aplicado
  weights: "imagenet"              # Pesos pre-entrenados a utilizar

# Configuración de preprocesamiento de imágenes
preprocessing:
  mode: "tf"                       # Modo de preprocesamiento (tf = TensorFlow standard)
  interpolation: "bilinear"        # Método de interpolación para resize

# Configuración de pruning (poda de parámetros) - actualmente deshabilitado
pruning:
  enabled: false                   # Habilitar/deshabilitar pruning
  schedule_type: "PolynomialDecay" # Tipo de schedule para pruning
  initial_sparsity: 0.0           # Sparsity inicial (0% de parámetros podados)
  final_sparsity: 0.5             # Sparsity final (50% de parámetros podados)
  begin_step: 0                   # Paso inicial del pruning
  end_step: 100                   # Paso final del pruning
  frequency: 10                   # Frecuencia de aplicación del pruning

# Configuración de entrenamiento
training:
  optimizer: "adam"                # Optimizador utilizado para fine-tuning

# Configuración de cuantización para TensorFlow Lite
quantization:
  enabled: true                    # Habilitar cuantización
  optimization: ["DEFAULT"]        # Tipo de optimizaciones TFLite
  representative_dataset_samples: 100  # Número de muestras para calibración
  supported_ops: ["TFLITE_BUILTINS_INT8"]  # Operaciones soportadas en cuantización

# Configuración de inferencia
inference:
  batch_size: 1                   # Tamaño de batch para inferencia
  num_threads: 1                  # Número de hilos para procesamiento
  use_xnnpack_delegate: false     # Usar delegate XNNPACK para CPU (deshabilitado)

# Configuración de datos
data:
  train_path: "data/train"         # Ruta relativa a datos de entrenamiento
  val_path: "data/val"            # Ruta relativa a datos de validación
  test_path: "data/test"          # Ruta relativa a datos de test
  classes: ["Blight", "Common_Rust", "Gray_Leaf_Spot", "Healthy"]  # 4 clases de enfermedades

# Configuración de validación y objetivos de rendimiento
validation:
  target_accuracy: 0.85           # Accuracy mínimo requerido (85%)
  target_size_reduction: 5        # Factor mínimo de reducción de tamaño
