model:
  name: "MobileNetV3Large"
  input_shape: [224, 224, 3]
  alpha: 1.0
  minimalistic: false
  include_top: true
  pooling: "avg"
  weights: "imagenet"

preprocessing:
  mode: "tf"
  interpolation: "bilinear"

pruning:
  enabled: false
  schedule_type: "PolynomialDecay"
  initial_sparsity: 0.0
  final_sparsity: 0.5
  begin_step: 0
  end_step: 100
  frequency: 10

training:
  optimizer: "adam"

quantization:
  enabled: true
  optimization: ["DEFAULT"]
  representative_dataset_samples: 100
  supported_ops: ["TFLITE_BUILTINS_INT8"]

inference:
  batch_size: 1
  num_threads: 1
  use_xnnpack_delegate: false

data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  classes: ["Blight", "Common_Rust", "Gray_Leaf_Spot", "Healthy"]

validation:
  target_accuracy: 0.85
  target_size_reduction: 5
